name: Aliyunpan-Actions

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 */4 * * *
  watch:
    types: started
jobs:
  run-it:
    runs-on: ubuntu-latest
    name: Aliyunpan-Actions
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: WebDAV-Install
        run: wget 'https://github.com/zxbu/webdav-aliyundriver/releases/download/v2.4.1/webdav-2.4.1.jar' --no-check-certificate && sudo chmod a+x webdav-2.4.1.jar
      - name: Rclone-Install
        run: wget 'https://raw.githubusercontent.com/wekingchen/my-file/master/rclone/rclone.zip' --no-check-certificate && sudo unzip rclone.zip && sudo chmod a+x rclone && sudo rm -f rclone.zip
      - name: WebDAV-Run
      env:
          aliyundrive_refresh_token: ${{ secrets.aliyundrive_refresh_token }}
        run: nohup java -jar webdav.jar --aliyundrive.refresh-token="$aliyundrive_refresh_token" &
      - name: Rclone-Config
        env:
          PANSYNC_RCLONE_CONFIG: ${{ secrets.PANSYNC_RCLONE_CONFIG }}
        run: |
          # 写配置文件
          mkdir -p ~/.config/rclone/
          cat << EOF > ~/.config/rclone/rclone.conf
          $PANSYNC_RCLONE_CONFIG
          EOF
      - name: Rclone-Run
        run: |
          # Rclone-Run

          # 延迟函数
          delay()
          {
          random_time=$(($RANDOM % $1))
          echo "等待 ${random_time} 分钟后开始同步"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时 $[${random_time}-$i] 分钟"
          sleep 1m
          done
          }

          # 随机延迟0~15分钟后再进行操作,可自行设置时间
          delay 1

          # 更改时区
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

          java -version
          echo "同步完毕"

